[tool.poetry]
name = "bib2graph"
version = "0.1.1"
description = ""
authors = ["complexluise <lhiguerac@unal.edu.co>"]
readme = "README.md"
package-mode = true

[tool.poetry.scripts]
bib2graph = "bib2graph.cli:main"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.0.0"
bibtexparser = "^1.4.0"
requests = "^2.31.0"
crossrefapi = "^1.5.0"
elsapy = "^0.5.0"
networkx = "^3.1"
pys2 = "^1.1.0"
neomodel = "^5.4.5"
lxml = "^5.4.0"
matplotlib = "^3.10.3"
seaborn = "^0.13.2"
notebook = "^7.4.2"
scipy = "^1.15.3"
tqdm = "^4.66.1"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
