[tool.poetry]
name = "bibliometria-sobre-cadena-semiconductores"
version = "0.1.0"
description = ""
authors = ["complexluise <lhiguerac@unal.edu.co>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.0.0"
py2neo = "^2021.2.3"
bibtexparser = "^1.4.0"
requests = "^2.31.0"
crossrefapi = "^1.5.0"
elsapy = "^0.5.0"
networkx = "^3.1"
pys2 = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
